Adding ui-checkbox element.
untangled-web/untangled-components pull request #31
Opened 2017-02-22 00:42 UTC by kklane

2017-02-23 16:12 UTC, awkay requested changes

2017-02-23 16:12 UTC, awkay commented on src/main/untangled/ui/elements.cljc
> +        attrs (cond-> attrs
Drop the `cond`. If everything should be done, then it isn't conditional :)

Also assoc and dissoc can do more than one at a time:

```
(-> attrs 
    (assoc :type "checkbox" :className classes :id (name id))
    (dissoc :styles))
```

2017-02-23 16:12 UTC, awkay commented on src/main/untangled/ui/elements.cljc
> +                        )
Style guide: no closing brace of any kind should start the non-whitespace of a line. Join this up to the line above.

2017-02-23 16:12 UTC, awkay commented on src/main/untangled/ui/elements.cljc
> +                      :always (dissoc :styles)
Type: I think you mean style...but I would not use that, since it has an HTML meaning.  See above comments on API of this method.

2017-02-23 16:12 UTC, awkay commented on src/main/untangled/ui/elements.cljc
> +    ))
Dangling parens

2017-02-23 16:12 UTC, awkay commented on src/main/untangled/ui/elements.cljc
> +  style (optional):  is-indeterminate :c-checkbox--informative"
What you want is:

`:checked` - Can be one of `true`, `false`, or `:indeterminate`

that way it is compatible with normal checkbox use (true/false), but can support the additional case.

`:style` should *never* be used in our elements, since it is an HTML predefined attribute.

You can use `(identical? true v)` to check that something is the actual boolean value true (or false for that matter).

2017-02-23 16:12 UTC, awkay commented on src/visuals/untangled/ui/element_visuals.cljs
> +    (e/ui-checkbox {:id "checkbox" :style #{:c-checkbox--informative}} )
API should never talk about CSS classes (you're mixing a CSS stye name into a user-visible API). It should be abstract.

2017-03-06 17:29 UTC, stephenway commented on src/main/untangled/ui/elements.cljc
> +  (let [legal-styles #{:is-indeterminate :c-checkbox--informative}
Informative has been removed as it's an internal-only class we don't need in this project.

2017-03-07 16:37 UTC, awkay commented
Merged manually. Still needs fixes, but cannot continue waiting for requested changes.

2017-03-07 16:37 UTC, closed without merging