Items added to elements: Avatar, loader, icons (adds standardized color and sizes) and notifications
untangled-web/untangled-components pull request #32
Opened 2017-02-22 00:48 UTC by rytomlinson

2017-02-23 16:12 UTC, awkay requested changes

2017-02-23 16:12 UTC, awkay commented on src/main/untangled/ui/elements.cljc
> +        props (cond-> props
This is just a thread. (e.g. get rid of `cond` and the `:always` bits:

`(-> props (assoc :className classes) (dissoc :size :color))`

2017-02-23 16:12 UTC, awkay commented on src/guide/untangled/ui/element_cards.cljs
> +                  ))
It's ok to leave these dangling while coding, but join them up onto the last line. There should never be a line that starts with a closing brace of any kind.

2017-02-23 16:12 UTC, awkay commented on src/guide/untangled/ui/element_cards.cljs
> +                  ))
Dangling parens

2017-02-23 16:12 UTC, awkay commented on src/main/untangled/ui/elements.cljc
> +(defn ui-notification
Not sure this is the right API for this. Generally content goes into an element as children. You claim to support children, but then don't render them.

Typical react would have you structure this more as:

```
(ui-notification {:type :warning}
  (ui-notification-heading { ... optional props ... } heading children)
  children-for-content)
```

I'm not currently looking at how it renders...so this might not be right either. Is the heading optional? Is the content variable? Should the content be able to be formatted? 

Props, in general, are not great for general body content, because they aren't DOM. That is the purpose of children.

2017-02-23 16:12 UTC, awkay commented on src/main/untangled/ui/elements.cljc
> +        classes      (cond-> user-classes
As a note, you could have started with:

```
(cond-> (str user-classes " c-notification")
```

and then you would not need the `:always`

2017-02-23 16:12 UTC, awkay commented on src/main/untangled/ui/elements.cljc
> +                    :info (icon :info)
This is the default case, so perhaps you don't need to match it?

2017-02-23 16:12 UTC, awkay commented on src/main/untangled/ui/elements.cljc
> +  [{:keys [className color size] :as props :or {className ""}} child] ;TODO: SHould we allow children?
Hm. Will @stephenway CSS work with more than one child? A hand-written SVG is one child. An IMG is one child. I'm guessing the way your written it is fine.

2017-02-23 16:18 UTC, stephenway commented on src/main/untangled/ui/elements.cljc
> +  [{:keys [className color size] :as props :or {className ""}} child] ;TODO: SHould we allow children?
Currently it only supports 1, but the plan is to let it handle up to 4 images that will layout out in a miniature inline grid for things like group chat.

2017-02-24 05:23 UTC, rytomlinson commented on src/main/untangled/ui/elements.cljc
> +  (let [legal-types #{:success :warning :error :informative}
In several places we define a legal-xxxx set and then use it once.  Should we just put the set in the conditionals?

2017-02-24 16:19 UTC, awkay commented on src/main/untangled/ui/elements.cljc
> +  (let [legal-types #{:success :warning :error :informative}
Giving something a name gives the intention, which I kind of like. Embedding it in the logic leads to messier results, particularly when the set grows large.

2017-02-24 16:20 UTC, awkay approved these changes

2017-02-24 16:20 UTC, merged